apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/corrieriluca/training-ci-cd
    targetRevision: HEAD
    path: ./argocd-config
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
