apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/corrieriluca/training-ci-cd
    targetRevision: HEAD
    path: ./apps/demo-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: demo-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
