apiVersion: v2
name: demo-header-back
version: 1.0.0
description: "Demo application"
appVersion: "v3.0.0"
dependencies:
  - name: base-helm-chart
    alias: generic
    version: 0.3.1
    repository: https://dixneuf19.github.io/helm-charts-repo/
