generic:
  replicaCount: 1
  image:
    repository: eu.gcr.io/padok-playground/demo-header-back
    tag: v0.2.0
    pullPolicy: Always
  container:
    port: 8000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
preview:
  enabled: false
host: "demo-luca-terence.playground.padok.cloud"
