apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo
spec:
  entryPoints:
    - web
  routes:
  {{- if .Values.preview.enabled }}
    - match: Host(`{{ .Values.host }}`) && Headers(`{{ .Values.preview.header.name }}`, `{{ .Values.preview.header.value }}`)
      kind: Rule
      services:
        - name: {{ .Values.preview.service.name }}
          namespace: {{ .Values.preview.namespace }}
          port: http
  {{- else }}
    - match: Host(`{{ .Values.host }}`)
      kind: Rule
      services:
        - name: demo-app
          namespace: demo-app
          port: http
  {{- end }}